name: Build Formulas

on:
  push:
    branches:
      - 'releases/**'

jobs:
  prepare-release:
    runs-on: ubuntu-latest

    outputs:
      release_name: ${{ steps.check_release.outputs.release_name }}
      hash_autobuild: ${{ steps.check_status.outputs.hash_autobuild }}

    steps:
      - uses: actions/checkout@v2
      - id: check_release
        name: Check Release Name
        env:
          BRANCH_NAME: ${{ github.ref }}
        run: echo "::set-output name=release_name::${BRANCH_NAME/refs\/heads\/releases\//}"

      - id: validate_release
        name: Validate Release Name
        run: |
          echo "Release ${{ steps.check_release.outputs.release_name }}"

  build-windows:
    runs-on: windows-2019
    needs: prepare-release
    steps:
      - uses: actions/checkout@v2
      - uses: docker://ritclizup/rit-python3-builder
      - id: build_formulas_python
        name: Build And Compress Formulas Python
        run: |
          git config core.fileMode false
          git status
          chmod +x ./.github/build.sh
          ./.github/build.sh ritclizup/rit-python3-builder
          git status
      - run: |
          mkdir ../build_win
          copy * ../build_win /E /H
      - uses: actions/upload-artifact@master
        with:
          name: build_win
          path: ../build_win

  build-mac:
    runs-on: macos-latest
    needs: build_windows
    steps:
      - run: mkdir ../build_mac
      - uses: actions/download-artifact@master
        with:
          name: build_win
          path: ../build_mac
      - run: cd ../build_mac
      - uses: docker://ritclizup/rit-python3-builder
      - id: build_formulas_python
        name: Build And Compress Formulas Python
        run: |
          git config core.fileMode false
          git status
          chmod +x ./.github/build.sh
          ./.github/build.sh ritclizup/rit-python3-builder
          git status
      - uses: actions/upload-artifact@master
        with:
          name: build_mac
          path: ../build_mac


  build-linux:
    runs-on: ubuntu-latest
    needs: prepare-release
    steps:
      - run: mkdir ../build_linux
      - uses: actions/download-artifact@master
        with:
          name: build_mac
          path: ../build_linux
      - run: cd ../build_linux

      - uses: docker://ritclizup/rit-go-builder
      - id: build_formulas_go
        name: Build And Compress Formulas GO
        run: |
          git config core.fileMode false
          git status
          chmod +x ./.github/build.sh
          ./.github/build.sh ritclizup/rit-go-builder
          git status

      - uses: docker://ritclizup/rit-python3-builder
      - id: build_formulas_python
        name: Build And Compress Formulas Python
        run: |
          git config core.fileMode false
          git status
          chmod +x ./.github/build.sh
          ./.github/build.sh ritclizup/rit-python3-builder
          git status
      - uses: actions/upload-artifact@master
        with:
          name: build_linux
          path: ../build_linux

  generate-release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux, build-mac]
    steps:
      - uses: actions/download-artifact@master
        with:
          name: build_linux
          path: ./  
      - id: clean_up_unnecessary_files
        name: Clean up unnecessary files
        run: |
          find ./ -maxdepth 1 -type f ! -name README.md ! -name LICENSE -delete
          rm -rf ./.circleci ./.github
          touch release_${{ needs.prepare-release.steps.check_release.outputs.release_name }}
          git status

      - id: commit_changes
        name: Commit Changes
        uses: EndBug/add-and-commit@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          signoff: true
          message: "Auto Build Formulas"

      - id: check_status
        name: Check Status
        run: |
          git status
          git --no-pager log -1 --format='%H'
          echo "::set-output name=hash_autobuild::$(git --no-pager log -1 --format='%H')"

      - id: create_release
        name: Create Release
        uses: actions/create-release@v1
#        uses: GongT/actions-recreate-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.prepare-release.steps.check_release.outputs.release_name }}
          release_name: Release ${{ needs.prepare-release.steps.check_release.outputs.release_name }}
          draft: false
          prerelease: false
          commitish: ${{ needs.prepare-release.steps.check_status.outputs.hash_autobuild }}

#  release:
#    runs-on: ubuntu-latest
#
#    needs: build
#
#    steps:
#      - uses: actions/checkout@v2
#      - id: create_release
#        name: Create Release
#        uses: GongT/actions-recreate-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ needs.build.outputs.release_name }}
#          release_name: Release ${{ needs.build.outputs.release_name }}
#          draft: false
#          prerelease: false  